### ISSUE TITLE
validate item keys for agent completion

### ISSUE THREAD

**Issue by asaveljevs** [zabbix/zabbix-bash-completion#5]
For Zabbix agent key completion, the output of "zabbix_agentd -p" command is used to parse suggestions. Unfortunately, not all suggested options are valid item keys. For instance:

```
$ zabbix_agentd -t 
[                 ...        ...        system.hw.devices      vfs.dev.write[
00:1f.2           ...        ...        system.hw.macaddr      vfs.file.cksum[
...               ...        ...        ...                    ...
logrt[            ...        ...        <tr><td                web.page.get[
math.seq          ...        ...        <tr><th                web.page.perf[
net.dns[          ...        ...        vfs.dev.read[          web.page.regexp
```

It can be seen that `[`, `00:1f.2`, `<tr><td`, and `<tr><th` are not valid item keys. Until [ZBXNEXT-3025](https://support.zabbix.com/browse/ZBXNEXT-3025) is implemented, we might wish to do manual validation.

**Comment by richlv** [comment]
should be fixed by b8582084c395ee1cd892bd630acdefac66a11af3
