### ISSUE TITLE
zabbix 6.2 and Azure

### ISSUE THREAD

**Issue by RobertoCifre38** [zabbix/zabbix-bash-completion#7]
Hello 

I'm trying to see the consumer credits for a machine.

I have done all the azure config, I have the zabbix app and in zabbix I have created some macros for a host (appId, password id etc etc) but when creating the item it tells me unknown azure.vm.cpu.credits.remaining

The key is azure.vm.cpu.credits.remaining and the jason Path is $.metrics.CPUCreditsRemaining.average as shown in the Zabbix 6.2 documentation

**Comment by richlv** [comment]
Hi, you probably intended to post in some general Zabbix support channel, it does not seem to be bash completion related.
Closing.
